export const mockApiData = [ { id: '0',
    label: 'Your requested items',
    primaryDetail: 'Amoxicillin 500mg Tablets',
    secondaryDetail: '20 Tablets',
    price: '0.00',
    hasCheckBox: true,
    canChange: true,
    canRemove: true },

  { addressLine1: 'REGIONAL REHABILITATION UNIT',
    addressLine2: 'CANADA HOUSE, RAWLINSON ROAD',
    addressLine3: null,
    addressLine4: 'ALDERSHOT',
    addressLine5: 'HAMPSHIRE',
    contactTelephoneNumber: null,
    email: null,
    langitude: null,
    latitude: null,
    mobileNumber: null,
    postcode: 'GU11 2LQ',
    practiceCode: 'A91158',
    practiceId: null,
    practiceName: 'RRU ALDERSHOT',
    preferredMethodOfCommunication: null,
    status: null },

  { town: "Nottingham",
    street: "76 Bracebridge Drive",
    countryCode: "GB",
    locality: "Bilborough",
    county: "Nottinghamshire",
    postcode: "NG8 4PH"}]